name: dart_package_template
version: 1.0.0
homepage: https://github.com/marchdev-tk/dart_package_template
description: dart_package_template description

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.9.4
