name: dart_package_template
version: 1.0.0
homepage: https://github.com/marchdev-tk/dart_package_template
repository: https://github.com/marchdev-tk/dart_package_template
issue_tracker: https://github.com/marchdev-tk/dart_package_template/issues
description: dart_package_template description

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  flutter_lints: ^1.0.0
  test: ^1.16.5
